### ISSUE TITLE
'Dart SDK overview' page issue

### ISSUE THREAD

**Issue by DanTup** [dart-lang/site-shared#102]
Page URL: https://www.dartlang.org/tools/sdk/
Page source: https://github.com/dart-lang/site-shared/tree/master/src/tools/sdk/index.md

On https://dart.dev/tools/sdk there's a block box that says:

> Note: This site’s documentation and examples use version 2.4 of the Dart SDK

The text "2.4" links to https://api.dart.dev/stable/2.4.0/2.4/index.html but that's a 404. It looks like it should be https://api.dart.dev/stable/2.4.0/index.html

I did look at the source, but this isn't hard-coded in the page, it comes from some Jekyll tags, so I'm not exactly sure where it should be fixed.

**Comment by kwalrath** [comment]
If you reload the page, it should work for you. We fixed this in https://github.com/dart-lang/site-www/pull/1728 (which _just_ made it to the website).

**Comment by DanTup** [comment]
Yep, looks good now 👍
