### ISSUE TITLE
Move to dart-lang

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-shared#11]
I just talked to @kevmoo, and he's ready to move this repo to dart-lang. He says you should be able to make a request to transfer ownership, and then we can fix up references after the move.

**Comment by kevmoo** [comment]
Maybe make me an owner on your repo – then I can start the transfer?

**Comment by chalin** [comment]
So we can transfer in two steps? Ok, let's try that.

**Comment by chalin** [comment]
Request sent.

**Comment by kevmoo** [comment]
https://github.com/dart-lang/site-shared There we go...

**Comment by chalin** [comment]
Thanks. Could you give similar permissions to what I had before (so I can create branches directly in this repo, etc).

I'll fix the references under site-www and site-webdev.

**Comment by kevmoo** [comment]
Done!

**Comment by kevmoo** [comment]
@kwalrath @chalin – can close this?
