### ISSUE TITLE
Update GitHub repository settings

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-shared#152]
- [x] [Switch default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch) to the new [`main` branch] (https://github.com/dart-lang/site-shared/tree/main) and delete the old `master` branch.
- [x] Enable [squash and merge](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) for easier to track Git history

\cc @kevmoo Could you help with this if you get a chance? Thanks for your help always!

**Comment by kevmoo** [comment]
I can disable merge commits for you?

**Comment by kevmoo** [comment]
Do you want me to do the master -> main switch now?

**Comment by parlough** [comment]
> I can disable merge commits for you?

That would be great. Thanks!

> Do you want me to do the master -> main switch now?

I just fixed the tests on the `main` branch and everything seems good to go on the `site-www` and `flutter/website` end. GitHub redirects links from the deleted `master` branch to the new default branch and the downstream submodules refer to commits anyway.

**Comment by parlough** [comment]
Thanks!
