### ISSUE TITLE
[code_excerpt] Unable to run on Windows

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/site-shared#198]
```console
 X:\SDK\flutter-master\bin\cache\dart-sdk\bin\dart.exe run build_runner build --delete-conflicting-outputs --config excerpt --output="X:\Coding\Garages\GitHub\flutter.cn\tmp\_fragments"                                                 
[INFO] Generating build script completed, took 294ms
[INFO] Reading cached asset graph completed, took 103ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 94ms
[INFO] Caching finalized dependency graph completed, took 91ms
[SEVERE] No assets exist in X, skipping output
[SEVERE] Unable to create merged directory for \Coding\Garages\GitHub\flutter.cn\tmp\_fragments.
[SEVERE] Failed after 210ms

```

**Comment by parlough** [comment]
Thanks for reporting this Alex!

Does it work when you don't specify the output? Did this workflow work before but stop recently?

**Comment by AlexV525** [comment]
> Does it work when you don't specify the output? Did this workflow work before but stop recently?

Unfortunately it never runs with or without the output specified. Neither with Windows Native or Git Bash on Windows.

**Comment by parlough** [comment]
I'm working on an overhaul of the tool now to make it much simpler, and I'll do my best to make sure it works on Windows too.

**Comment by parlough** [comment]
The sites are now using the rewritten tool, which should support Windows, but if any issues pop up, let me know. Thanks!
