### ISSUE TITLE
Clarify process of contributing to site-shared

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-shared#36]
We've had at least a couple of contributors try to make improvements to files under site-shared by creating a PR for site-www or site-webdev.

We should somehow make clear (maybe in these files? maybe in the CONTRIBUTING.md files of sites that use site-shared?) that changes to files under site-shared need to be made to the site-shared repo.

Related: dart-lang/site-webdev#1813

**Comment by kwalrath** [comment]
A similar issue is contributions to other sub-repos. E.g. dart-lang/site-webdev#1809 broke the build because it fixed an angular typo. We should have instead fixed the issue in the angular repo.

**Comment by chalin** [comment]
> We should have instead fixed the issue in the angular repo.

One solution would be to avoid committing the notes sources (since they are autogenerated). Initially I just thought that it was convenient to be able to see the rendered sources.

**Comment by kwalrath** [comment]
>> We should have instead fixed the issue in the angular repo.

> One solution would be to avoid committing the notes sources (since they are autogenerated). Initially I just thought that it was convenient to be able to see the rendered sources.

Wouldn't we see them if we did a real build (similar to the API doc situation)? Also, this is independent of the problem of the github and bug links going to the wrong repo, right?

**Comment by chalin** [comment]
> Wouldn't we see them if we did a real build (similar to the API doc situation)?

Yes.

> Also, this is independent of the problem of the github and bug links going to the wrong repo, right?

Right.
