### ISSUE TITLE
Add path info to Dart SDK page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-shared#37]
_From @oneyb on August 31, 2018 16:14_

From URL: https://webdev.dartlang.org/tools/sdk/

It would be good to include complete installation information. This means adding the sdk directory to the PATH. #19926 

You know after installing the binaries:

```bash
echo 'export PATH="/usr/lib/dart/bin:$PATH"' >> $HOME/.profile
```

_Copied from original issue: dart-lang/site-webdev#1812_

**Comment by kwalrath** [comment]
I think we used to do this. I don't know why we stopped, but it does seem like a good thing to do.

**Comment by chalin** [comment]
> echo 'export PATH="/usr/lib/dart/bin:$PATH"' >> $HOME/.profile

IMHO this is way too specific an instruction to include on that page, that makes various assumptions about how the user's environment is setup and his/her preferred way of updating the PATH variable. I'd rather just say, something along the lines of "update your path". @kwalrath WDYT?

**Comment by kwalrath** [comment]
Agreed that we don't want to be overly specific, but sometimes we can provide a little distribution-specific help on where to find the binaries. E.g. homebrew has a certain setup that can be hard to figure out. We could also link to where they can find help on setting the PATH.

But the very least we should do is remind them to add the commands to their PATH.

**Comment by oneyb** [comment]
Comments would be good. I meant it for the Linux tab.

I made a pull request, which doesn't seem to be passing:

https://github.com/dart-lang/site-webdev/pull/1813 

but will move it to this repo. No wonder I was confused.

**Comment by kwalrath** [comment]
Yes, the contribution process for shared pages is very confusing, and I've filed issues to clarify it (e.g. #36). Thanks for sticking with this, @oneyb!
