### ISSUE TITLE
"Ruby Sass is deprecated and will be unmaintained as of 26 March 2019."

### ISSUE THREAD

**Issue by filiph** [dart-lang/site-shared#80]
This is a message you get when installing github.com/flutter/website (last step). @chalin, I assume this is not a trivial change. Can you look at filing it as a proper "replace ruby sass with dart sass" bug here (or wherever it makes most sense)? You have way more context than I do.

**Comment by chalin** [comment]
Here's the original issue I opened over this: https://github.com/flutter/website/issues/1175

**Comment by parlough** [comment]
Closing as updating to Jekyll 4 with the infrastructure updates no longer uses Ruby Sass. Thanks!
