### ISSUE TITLE
Update external links to wiki to point to /doc files.

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-shared#84]

**Comment by sidx8** [comment]
hello
 I'm interested in this issue can I start working on it...

**Comment by kwalrath** [comment]
@sidx8 yes, please!

**Comment by sidx8** [comment]
#117 is this the way it's supposed to be I didn't add any description to the links though I didn't know if you wanted that.

**Comment by kwalrath** [comment]
I think this is done, but I'm going to leave this open as a reminder to update links from other sites.
