### ISSUE TITLE
'Dart SDK overview' page issue

### ISSUE THREAD

**Issue by hiko1129** [dart-lang/site-shared#95]
Page URL: https://www.dartlang.org/tools/sdk/
Page source: https://github.com/dart-lang/site-shared/tree/master/src/tools/sdk/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

There is a Broken link.

[Note: This site’s documentation and examples use version [2.3.0-dev.0.5](https://api.dartlang.org/stable/2.3.0-dev.0.5/index.html) of the Dart SDK.]

[https://api.dartlang.org/stable/2.3.0-dev.0.5/index.html] is nonexistent link.

**Comment by kwalrath** [comment]
This looks like it's been fixed with the update to 2.3. Please reload and let me know if I'm wrong.
