### ISSUE TITLE
'Dart SDK Archive' page issue

### ISSUE THREAD

**Issue by rootext** [dart-lang/site-shared#96]
Page URL: https://www.dartlang.org/tools/sdk/archive/
Page source: https://github.com/dart-lang/site-shared/tree/master/src/tools/sdk/archive/index.md

Description of issue:
It's not an issue but improvement proposal.
This page makes a lot of requests (500+) to https://storage.googleapis.com/dart-archive/channels/.../release/.../VERSION on loading. It leads to UI freezes.
It would be better to make request on demand, when user picks specific version on dropdown.

**Comment by kwalrath** [comment]
Related: #97.

/cc @johnpryan, @domesticmouse
