### ISSUE TITLE
Move Dart SDK pages from site-shared to site-www

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-shared#99]
/src/tools/sdk used to be shared with webdev.dartlang.org. It no longer is, so hosting the page content here just adds overhead. (Witness the 2 PRs I had to create to make small changes to the tool & SDK pages: #98 & dart-lang/site-www#1665.)

/cc @johnpryan @sfshaza2

**Comment by johnpryan** [comment]
This might also be an opportunity to clean up some of the symlinks throughout the site, for example: 

```
src/tools/sdk -> src/_shared/tools/sdk
src/_shared -> site-shared
```

**Comment by kwalrath** [comment]
I’m going to work on this today. It’s really annoying (and slows us down) to have to update subprojects for a change that’s only visible on dart.dev!
